/**
 * src/lib/war-plan.ts —— 「作战思路」的素材组装、时段缓存与采纳（v1.6 重做作战板块）。
 *
 * ## 这一版把「作战」页的产物换掉了什么
 *
 * 旧版作战页只**展示**数据，决策全交回用户：自己在复盘页写预期、自己在 Q1/Q2/Q3 卡上
 * 点选答案、自己逐条判竞价。新版反过来 —— **模型给作战思路**（主攻方向 / 候选票 /
 * 触发与失败条件 / 三问落点 / 持仓动作 / 竞价判定），用户只做采纳、修改或驳回。
 *
 * ## 「以其他板块为基础，不是空穴来风」在这里怎么落地
 *
 * 两层：
 *   1. **素材层（本文件）**：思路的输入**全部**取自其他页面的真实产出 ——
 *      行情页（广度/温度计/板块榜/涨停梯队）、自挖板块页（市场自聚类 + 强度分）、
 *      选股筛选页（全 A 快照，与行情页同源）、复盘页（存档的预期清单/主线/风险备注）、
 *      竞价雷达（竞价特征 + 系统初判）、事件流与板块脉冲、持仓台账与自选。
 *      **不给它别的东西，也绝不让它自己去取数** —— 模型看到的正是用户屏幕上那份；
 *   2. **护栏层（`lib/war-plan-guard.ts`）**：模型只能说素材里出现过的票与板块名，
 *      引文要能逐字/数字反查。越界的东西被剔除并**显示出来**。
 *
 * ## 成本纪律（与全仓同一条口径）
 *
 *   · **不新增任何轮询**：思路只在「页面打开 / 时段切换 / 用户点重算」时生成，
 *     按 `${day}:${stage}` 缓存（同一时段内重复打开 = 0 次模型调用，页头显示这件事）；
 *   · **非交易时段不自动生成**：休市期没有盘面素材，自动跑一次模型只会得到
 *     "证据不足"——那是一次白花的调用（`autoGenerateDecision` 把这条纪律写成了纯函数）；
 *   · 自挖板块素材走**已有的** `hist_concept_classes`（引擎快照，服务端缓存），
 *     不额外命名、不额外采集 —— 命名那一路的开销与缓存属于「自挖板块」页，这里不碰。
 */
import type { WarPlan } from './ai-contract'
import type { Stage } from './stage'
import type { SessionPhase } from './session-clock'
import type { Situation } from './situation'
import { situationShortLabel } from './situation'
import type { Regime } from './regime'
import type { Breadth } from './market'
import type { BoardStat, LadderSnapshot } from './ladder'
import type { AShareRow } from './stock-data'
import type { EventItem } from './event-stream'
import type { BoardPulse } from './board-pulse'
import type { Position } from './positions'
import type { ExpectItem } from './review-store'
import type { WatchItem } from './watchlist-store'
import type { ConceptClassRow } from './naming'
import type { Verdict } from './auction-analysis'
import { NAMING_PARAMS_FALLBACK } from './naming'
import { compareByStrength } from './concept-strength'
import { filterUsableClasses } from './concept-quality'
import { onHostHydrated, syncTable } from './host-state'
import { getLatestPlan, today } from './review-store'
import {
  ensureDayRun,
  getDayRun,
  setQ1,
  setQ2,
  setQ3Idle,
  setQ3Symbol,
  setVerdict,
} from './dayrun'

// ────────────────────────────── 素材（输入） ──────────────────────────────

/** 竞价时段的一行竞价特征（由 `.mcp__local__auction` 逐票算出，与竞价雷达同口径）。 */
export interface WarAuctionRow {
  symbol: string
  name: string
  /** 竞价末端价 vs 昨收（%）。 */
  openPct: number
  climaxDir: 'buy' | 'sell' | 'none'
  nearLimit: boolean
  fakeBigThenDrop: boolean
  /** 昨日预期状态（该票在预期清单里时）。 */
  expectState?: ExpectItem['state']
  /** 系统初判（`judgeExpectation`，与竞价雷达同一函数）。 */
  autoVerdict?: Verdict
}

/**
 * 一次作战思路的**全部素材**（每一项都对应一个已有页面的产出；缺失就是缺失，不补空）。
 *
 * 为什么用具体类型而不是 `unknown`：组装层是"其他板块 → 作战板块"的唯一接口，
 * 类型写死才能让"某个页面改了字段名"在编译期就炸，而不是模型悄悄少看一块。
 */
export interface WarMaterials {
  day: string
  stage: Stage
  phase: SessionPhase
  /** 当前时刻 HH:MM。 */
  clockText: string
  /** 盘中窗口说明（验证窗 / 主段 / 尾盘）。 */
  windowNote: string
  breadth: Breadth | null
  regime: Regime | null
  situation: Situation | null
  ladder: LadderSnapshot | null
  events: EventItem[]
  pulses: BoardPulse[]
  /** 可采信的自挖类（已过弱链/传递链筛选，按强度降序）。null = 引擎没取到。 */
  concepts: ConceptClassRow[] | null
  /** 自挖板块素材的说明（as_of / 可用类数 / 排除了几个）。 */
  conceptsNote: string
  /** 池内却孤立的强势票（"独狼"，自挖板块页也会列出来）。 */
  isolatedTop: Array<{ symbol: string; name: string; chgPct: number | null; limitUp: boolean }>
  /** 选股筛选（预设「放量上攻」）命中：涨停梯队之外那批"没封板但在放量"的票。 */
  screened: AShareRow[]
  positions: Position[]
  watchlist: WatchItem[]
  /** 最近一份复盘存档的预期清单（"用户原来想打什么"，作为输入之一而不是答案）。 */
  myPlan: { day: string; expectations: ExpectItem[]; mainLine: string[]; riskNote: string } | null
  /** 竞价特征（仅竞价/盘前时段非空）。 */
  auctions: WarAuctionRow[]
  /** 素材缺口说明（"自挖板块引擎不可用"…）—— 进 prompt，也进界面。 */
  missing: string[]
}

/** 素材条数上限（体量纪律：`AI_CONTEXT_MAX_BYTES` = 24KB，这里留足余量）。 */
export const MATERIAL_CAPS = {
  boards: 15,
  concepts: 8,
  conceptMembers: 10,
  ladder: 20,
  events: 15,
  pulses: 8,
  positions: 8,
  watchlist: 15,
  expectations: 5,
  isolated: 8,
  auction: 8,
  screener: 8,
} as const

/** 保留两位（模型不需要 8 位小数；也省 token）。 */
function r2(v: unknown): number | null {
  const n = typeof v === 'number' ? v : Number(v)
  if (!Number.isFinite(n)) return null
  return Math.round(n * 100) / 100
}

/** 符号（market+code → 标准符号）。 */
function sym(market: string, code: string): string {
  return `${market.toUpperCase()}${code}`
}

/**
 * 组装喂给模型的上下文（**纯函数**：同样的素材 → 同样的上下文，便于单测与追溯）。
 *
 * `sectorUniverse` 是护栏的"允许方向名"白名单，必须由组装方显式声明：
 * 现在它 = 行情页板块榜名（涨停家数排序的官方板块名）。**自挖类没有名字**
 * 是刻意的 —— 给类起名是「自挖板块」页的模型调用，作战页不该偷偷再花一次预算；
 * 类的作用是把"哪一批票在共动"作为**证据**（成员表）交给模型。
 */
export function buildWarContext(m: WarMaterials): Record<string, unknown> {
  const boards = (m.ladder?.boards ?? []).slice(0, MATERIAL_CAPS.boards)
  const sectorUniverse = boards.map((b) => b.name).filter((n) => n !== '')

  const boardsOut = boards.map((b: BoardStat) => ({
    name: b.name,
    limitUpCount: b.limitUpCount,
    pct: r2(b.pct),
    rep: b.rep,
    repSymbol: b.repCode === '' ? null : sym(b.rep === '' ? 'SH' : boardMarketOf(b), b.repCode),
  }))

  const conceptsOut = (m.concepts ?? []).slice(0, MATERIAL_CAPS.concepts).map((c) => ({
    id: c.classId,
    size: c.size,
    strength: r2(c.strength),
    chgMean: r2(c.chgMean),
    limitUpN: c.limitUpN,
    intraCorr: r2(c.intraCorr),
    strongDensity: r2(c.strongDensity),
    members: c.members.slice(0, MATERIAL_CAPS.conceptMembers).map((mem) => ({
      symbol: sym(mem.market, mem.code),
      name: mem.name,
      pct: r2(mem.chgPct),
      limitUp: mem.limitUp,
    })),
  }))

  return {
    day: m.day,
    stage: m.stage,
    phase: m.phase,
    clock: m.clockText,
    window: m.windowNote,
    /** 方向名白名单（护栏按它逐字反查 `sectors[].name`）。 */
    sectorUniverse,
    market: {
      breadth: m.breadth === null ? null : {
        up: m.breadth.up,
        down: m.breadth.down,
        flat: m.breadth.flat,
        limitUp: m.breadth.limitUp,
        limitDown: m.breadth.limitDown,
        strongUp: m.breadth.strongUp,
        strongDown: m.breadth.strongDown,
        amountYi: r2(m.breadth.amountSum / 1e8),
        avgPct: r2(m.breadth.avgPct),
      },
      regime: m.regime === null ? null : {
        temperature: m.regime.temperature,
        band: m.regime.band,
        drivers: m.regime.drivers,
      },
      situation: m.situation,
      limitDownCount: m.ladder?.limitDownCount ?? null,
    },
    boards: boardsOut,
    concepts: conceptsOut,
    conceptsNote: m.conceptsNote,
    isolated: m.isolatedTop.slice(0, MATERIAL_CAPS.isolated).map((s) => ({
      symbol: s.symbol,
      name: s.name,
      pct: r2(s.chgPct),
      limitUp: s.limitUp,
    })),
    /**
     * 选股筛选（预设「放量上攻」）的命中。
     *
     * 为什么单列一块而不是并进 ladder：ladder 是"已经封板"的票，这一块是"在放量但没封板"
     * 的票 —— 后者的信息量恰好在于"还没走完"，也正好是选股筛选页的口径
     * （`lib/screener` 的同一份预设，零额外请求：全 A 快照本来就在手上）。
     */
    screened: m.screened.slice(0, MATERIAL_CAPS.screener).map((r) => ({
      symbol: sym(r.market, r.code),
      name: r.name,
      pct: r2(r.pct),
      volRatio: r2(r.vol_ratio),
      turnover: r2(r.turnover),
      amountYi: r2((r.amount ?? 0) / 1e8),
    })),
    ladder: (m.ladder?.limitUp ?? []).slice(0, MATERIAL_CAPS.ladder).map((s) => ({
      symbol: sym(s.market, s.code),
      name: s.name,
      streak: s.streak,
      pct: r2(s.pct),
      amountYi: r2((s.amount ?? 0) / 1e8),
    })),
    events: m.events.slice(0, MATERIAL_CAPS.events).map((e: EventItem) => ({
      kind: e.kind,
      name: e.name,
      symbol: sym(e.market, e.code),
      time: e.time,
      desc: e.desc,
    })),
    pulses: m.pulses.slice(0, MATERIAL_CAPS.pulses).map((p: BoardPulse) => ({
      name: p.name,
      deltaLimitUp: p.deltaLimitUp,
      limitUp: p.limitUp,
      leader: p.leader?.name ?? null,
    })),
    positions: m.positions.slice(0, MATERIAL_CAPS.positions).map((p: Position) => ({
      symbol: p.symbol,
      name: p.name,
      entryPrice: r2(p.entryPrice),
      shares: p.shares,
      entryDate: p.entryDate,
      stopLoss: r2(p.plan.stopLoss),
      failIf: p.plan.failIf,
      expectState: p.expectState ?? null,
    })),
    watchlist: m.watchlist.slice(0, MATERIAL_CAPS.watchlist).map((w: WatchItem) => ({
      symbol: sym(w.market, w.code),
      name: w.name,
    })),
    myPlan: m.myPlan === null ? null : {
      day: m.myPlan.day,
      mainLine: m.myPlan.mainLine,
      riskNote: m.myPlan.riskNote,
      items: m.myPlan.expectations.slice(0, MATERIAL_CAPS.expectations).map((e: ExpectItem) => ({
        symbol: e.symbol,
        name: e.name,
        state: e.state,
        scenario: e.scenario,
        auctionOK: e.auctionOK,
        failIf: e.failIf,
        reason: e.reason,
      })),
    },
    auction: m.auctions.slice(0, MATERIAL_CAPS.auction).map((a) => ({
      symbol: a.symbol,
      name: a.name,
      openPct: r2(a.openPct),
      climaxDir: a.climaxDir,
      nearLimit: a.nearLimit,
      fakeBigThenDrop: a.fakeBigThenDrop,
      expectState: a.expectState ?? null,
      autoVerdict: a.autoVerdict ?? null,
    })),
    /** 素材缺口：让模型知道"自己少看了什么"，也让界面能解释"为什么它只说证据不足"。 */
    missing: m.missing,
  }
}

/**
 * 板块代表股的交易所前缀。
 *
 * `BoardStat` 只给了代表股**代码**（不带市场），而模型的符号必须是标准符号。
 * 按代码段推断（6/9 → SH，4/8 → BJ，其余 → SZ），与 `lib/ai-contract` 的
 * `normalizeSymbol` 同一口径 —— 这里显式写出来是为了让"推断"这件事可见。
 */
function boardMarketOf(b: BoardStat): string {
  const head = b.repCode.charAt(0)
  return head === '6' || head === '9' ? 'SH' : head === '4' || head === '8' ? 'BJ' : 'SZ'
}

/** 自挖板块素材的精简（筛选 + 排序 + 说明），供页面与上下文共用。 */
export function prepareConcepts(
  payload: { ok: boolean; asOf: string; classes: ConceptClassRow[]; notes: string[]; params?: { minCorr: number } } | null,
): { rows: ConceptClassRow[]; note: string } {
  if (payload === null || !payload.ok) {
    return { rows: [], note: `自挖板块引擎不可用：${payload?.notes.join('；') ?? '未取数'}` }
  }
  const minCorr = payload.params?.minCorr ?? NAMING_PARAMS_FALLBACK.minCorr
  const { usable, dropped } = filterUsableClasses(payload.classes, minCorr)
  const rows = [...usable].sort(compareByStrength).slice(0, MATERIAL_CAPS.concepts)
  return {
    rows,
    note:
      `as_of ${payload.asOf || '—'} · window ${NAMING_PARAMS_FALLBACK.window} / min_corr ${minCorr} / pool ${NAMING_PARAMS_FALLBACK.poolN}`
      + ` · 可用 ${usable.length} 类（用了前 ${rows.length}）· 排除 ${dropped.length} 个弱链/传递链可疑类`,
  }
}

/**
 * 符号 → 名称。
 *
 * 模型只给标准符号（护栏按符号查白名单），但界面上"SH600519"远不如"贵州茅台"可读 ——
 * 名称一律**从素材回查**（而不是让模型自己填，那样它就能编名字了）。
 * 查不到就显示符号本身（诚实：这个名字今天确实没出现在任何一块素材里）。
 */
export function nameIndexOf(m: WarMaterials): Map<string, string> {
  const map = new Map<string, string>()
  const put = (s: string, n: string): void => {
    if (s !== '' && n !== '' && !map.has(s)) map.set(s, n)
  }
  for (const p of m.positions) put(p.symbol, p.name)
  for (const w of m.watchlist) put(sym(w.market, w.code), w.name)
  for (const e of m.myPlan?.expectations ?? []) put(e.symbol, e.name)
  for (const s of m.ladder?.limitUp ?? []) put(sym(s.market, s.code), s.name)
  for (const c of m.concepts ?? []) for (const mem of c.members) put(sym(mem.market, mem.code), mem.name)
  for (const a of m.auctions) put(a.symbol, a.name)
  for (const s of m.isolatedTop) put(s.symbol, s.name)
  for (const r of m.screened) put(sym(r.market, r.code), r.name)
  for (const b of m.ladder?.boards ?? []) if (b.repCode !== '') put(sym(boardMarketOf(b), b.repCode), b.rep)
  return map
}

// ────────────────────────────── 自动生成纪律 ──────────────────────────────
/** 自动生成的判定结果（`why` 会显示在卡片上：让"为什么没自动跑"看得见）。 */
export interface AutoDecision {
  run: boolean
  why: string
}

/**
 * 该不该为当前时段自动生成一次作战思路（页面打开 / 时段切换各判一次）。
 *
 * 三条规则，全部来自既有纪律：
 *   1. **同一时段已有缓存** → 不跑（这是"打开页面就烧一次模型"的唯一刹车）；
 *   2. **没有盘面素材**（休市 / 取数失败 / 数据源不可达）→ 不跑；
 *      自动跑只会得到一句"证据不足"，白花一次调用（休市期不发起全量请求的同一立场）；
 *   3. 其余（竞价 / 盘中 / 尾盘，且素材在手）→ 跑一次。
 */
export function autoGenerateDecision(input: {
  hasMaterials: boolean
  existing: WarPlanRecord | null
  now: number
}): AutoDecision {
  if (input.existing !== null && planFreshness(input.existing, input.now) === 'fresh') {
    return { run: false, why: `已有时段内的思路（${hhmm(input.existing.at)} 生成，可重算）` }
  }
  if (!input.hasMaterials) {
    return { run: false, why: '没有可用的盘面素材（休市 / 取数失败）→ 不自动生成，省模型预算' }
  }
  return { run: true, why: '本时段第一次打开：自动生成一次' }
}

// ────────────────────────────── 时段缓存（持久化） ──────────────────────────────

/** 一份作战思路的存档（含"模型看到的是哪份素材"的元信息）。 */
export interface WarPlanRecord {
  day: string
  stage: Stage
  at: number
  plan: WarPlan
  /** 模型原文（结构化失败时的兜底，也是留痕）。 */
  raw: string
  provider: string
  model: string
  ms: number
  ctxBytes: number
  /** 自愈裁剪记录（有值 = 模型少看了东西，界面必须显示）。 */
  shrunk: string[]
  /** 白名单规模：模型这次能点名的票 / 能用的方向名（来自 host 半的护栏报告）。 */
  pool: { symbols: number; sectors: number }
  /** 素材缺口。 */
  missing: string[]
  /** 思路"属于哪个时段"的可读标签（竞价/盘中/尾盘/复盘）。 */
  stageLabel: string
  /**
   * 生成时**写进当日记录**的内容（"模型结论被采纳了多少"的留痕）。
   *
   * 为什么存在记录里而不是组件 state：刷新页面后这条痕迹必须还在 ——
   * 否则用户第二天回看"当时的三问是谁答的"就只能靠猜（`from: 'ai'` 只标了来源，
   * 没标这一轮补了哪几项）。
   */
  adopted: AdoptionResult
}

/** 同一时段内的思路多久算"新鲜"（过期只标记、不自动重算 —— 重算由用户决定）。 */
export const WAR_PLAN_TTL_MS = 30 * 60 * 1000

const STORAGE_KEY = 'dsh-stock-panel:war-plan:v1'
const MAX_RECORDS = 40

/** 记录键：一天里的每个时段各一份（竞价/盘中/尾盘/复盘各一次模型调用，不重复烧）。 */
export function planKey(day: string, stage: Stage): string {
  return `${day}:${stage}`
}

let records: Record<string, WarPlanRecord> = load()
const listeners = new Set<() => void>()

function load(): Record<string, WarPlanRecord> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw === null) return {}
    const parsed = JSON.parse(raw) as unknown
    if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) return {}
    const out: Record<string, WarPlanRecord> = {}
    for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
      if (v === null || typeof v !== 'object') continue
      const rec = v as WarPlanRecord
      if (typeof rec.day !== 'string' || typeof rec.at !== 'number' || rec.plan === undefined) continue
      out[k] = rec
    }
    return out
  } catch {
    return {}
  }
}

function persist(): void {
  try {
    const entries = Object.entries(records).sort((a, b) => b[1].at - a[1].at)
    records = Object.fromEntries(entries.slice(0, MAX_RECORDS))
    localStorage.setItem(STORAGE_KEY, JSON.stringify(records))
  } catch {
    /* 隐私模式/配额：忽略 */
  }
  // A1：host 域同步（键值表 → shape: 'keyed'）。
  syncTable('war_plans', records)
}

function notify(): void {
  for (const fn of listeners) {
    try {
      fn()
    } catch {
      /* ignore */
    }
  }
}

// A1：host 域数据落地后，用权威版本重载并通知 UI。
onHostHydrated(() => {
  records = load()
  notify()
})

/** 订阅思路存档变更（跨组件同步）。 */
export function subscribeWarPlan(fn: () => void): () => void {
  listeners.add(fn)
  return () => listeners.delete(fn)
}

/** 某日某时段的思路（无则 null）。 */
export function getWarPlan(day: string, stage: Stage): WarPlanRecord | null {
  return records[planKey(day, stage)] ?? null
}

/** 写入/覆盖一份思路存档。 */
export function saveWarPlan(rec: WarPlanRecord): void {
  records = { ...records, [planKey(rec.day, rec.stage)]: rec }
  persist()
  notify()
}

/** 丢掉某日某时段的思路（用户点「重算」前的清理，或想强制刷新）。 */
export function clearWarPlan(day: string, stage: Stage): void {
  const key = planKey(day, stage)
  if (!(key in records)) return
  const next = { ...records }
  delete next[key]
  records = next
  persist()
  notify()
}

/** 新鲜度（过期只是标注，不自动重算）。 */
export function planFreshness(rec: WarPlanRecord, now: number): 'fresh' | 'stale' {
  return now - rec.at <= WAR_PLAN_TTL_MS ? 'fresh' : 'stale'
}

/** HH:MM。 */
function hhmm(ts: number): string {
  const d = new Date(ts)
  return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`
}

/**
 * 回包结构不可用时的占位思路。
 *
 * 为什么要有它而不是"直接报错、什么都不存"：模型**确实说了话**（原文在 `raw` 里），
 * 「说了但结构不对」必须留痕并显示，否则用户看到的是"点了一下什么都没发生"。
 * 这条占位思路是 `insufficient`（不写任何当日记录），原因写明"回包不可用"。
 */
export function unusableWarPlan(reason: string): WarPlan {
  return {
    insufficient: true,
    reason,
    summary: '',
    stance: 'wait',
    sectors: [],
    picks: [],
    q1: null,
    q2: null,
    actions: [],
    verdicts: [],
    avoid: [],
    evidence: [],
    guard: { droppedSymbols: [], droppedSectors: [], ungrounded: [], grounded: 0, symbolPool: 0, sectorPool: 0 },
  }
}

// ────────────────────────────── 采纳（模型结论 → 当日记录） ──────────────────────────────

/** 采纳结果（哪些写进去了、哪些因为"你已经有答案"而保留原样）。 */
export interface AdoptionResult {
  /** 写进当日记录的项（人读文案）。 */
  written: string[]
  /** 保留原答案的项（人读文案）—— **绝不覆盖人工答案**。 */
  kept: string[]
}

/**
 * 把模型的三问落点 / 持仓动作 / 竞价判定**按默认值**写进当日运行记录。
 *
 * 语义（这是"模型给默认结论、用户可改可驳回"的落点）：
 *   · 只填**空位**：用户已经答过的（人工或更早的采纳）一律不动 —— 每次重新生成思路
 *     都只是"补齐没答的"，不会把人的判断反复覆盖掉；
 *   · 只写**素材里有的**持仓与预期（护栏在 host 半保证票在素材内；这里再按持仓台账
 *     与预期清单的事实过滤一次：思路可能基于几轮前的素材）；
 *   · 全部标记 `from: 'ai'`，Q 卡上显示「模型→」，人一点就变回人工。
 *
 * 副作用明确（写 dayrun），所以单独成函数、由组件在**生成成功后**调用一次。
 */
export function adoptWarPlan(day: string, plan: WarPlan, positions: Position[]): AdoptionResult {
  const written: string[] = []
  const kept: string[] = []
  if (plan.insufficient) return { written, kept }

  // 一次性读当日记录：每写一项都要重读（setXxx 会 upsert），但"是否已答"按最初始的快照判
  const before = getDayRun(day)
  if (plan.q1 !== null) {
    if (before?.q1 === undefined) {
      setQ1(day, plan.q1.value, 'ai')
      written.push(`Q1 ${q1Label(plan.q1.value)}`)
    } else {
      kept.push('Q1（已有人工答案，保留）')
    }
  }
  if (plan.q2 !== null) {
    if (before?.q2 === undefined) {
      setQ2(day, plan.q2.value, 'ai')
      written.push(`Q2 ${situationShortLabel(plan.q2.value)}`)
    } else {
      kept.push('Q2（已有人工答案，保留）')
    }
  }

  const held = new Set(positions.map((p) => p.symbol))
  for (const a of plan.actions) {
    // 只覆盖**当前持仓**：思路可能基于几轮前的素材，已清掉的票不该再写动作
    if (!held.has(a.symbol)) {
      kept.push(`${a.symbol} 动作（已不在持仓台账）`)
      continue
    }
    if (before?.q3?.bySymbol[a.symbol] !== undefined) {
      kept.push(`${a.symbol} 动作（已有人工答案，保留）`)
      continue
    }
    setQ3Symbol(day, a.symbol, a.action, 'ai')
    written.push(`${a.symbol} ${q3Label(a.action)}`)
  }
  // 空仓且模型也没给持仓动作 → 打「空仓观望」钩（无动作也是一种决策）
  if (positions.length === 0 && plan.actions.length === 0 && before?.q3?.idle !== true) {
    setQ3Idle(day, true)
    written.push('Q3 空仓观望')
  }

  // 竞价判定只对**预期清单里的票**有意义（清单外没有对照基准，判定不可证伪）
  const expectSymbols = latestExpectationSymbols()
  for (const v of plan.verdicts) {
    if (expectSymbols !== null && !expectSymbols.includes(v.symbol)) {
      kept.push(`${v.symbol} 判定（不在预期清单，保留未判）`)
      continue
    }
    if (before?.verdicts[v.symbol] !== undefined) {
      kept.push(`${v.symbol} 判定（已有人工答案，保留）`)
      continue
    }
    setVerdict(day, v.symbol, v.verdict, 'ai')
    written.push(`${v.symbol} ${v.verdict}`)
  }

  // 保证"这一天有记录"（即使三问都没落点，也要留下当天有思路的痕迹）
  ensureDayRun(day)
  return { written, kept }
}

/**
 * 最近一份复盘的预期清单符号（判定只对清单内的票有意义：清单外没有对照基准）。
 *
 * ⚠️ 这是本模块**唯一**的界面侧依赖（`review-store`），且本模块**只被 client 半引用**
 * （host 半只引 `ai-contract` + `war-plan-guard`）—— 别把 `war-plan.ts` 拖进 host 链路。
 * 读不到（存档为空/异常）返回 null = 不过滤，而不是把整批判定静默丢掉。
 */
function latestExpectationSymbols(): string[] | null {
  try {
    const plan = getLatestPlan(today())
    if (plan === null) return null
    return plan.expectations.map((e) => e.symbol)
  } catch {
    return null
  }
}

function q1Label(v: string): string {
  return v === 'strengthen' ? '增强' : v === 'weaken' ? '衰减' : '中性'
}

function q3Label(v: string): string {
  return v === 'hold' ? '持有' : v === 'reduce' ? '减仓' : v === 'clear' ? '清仓' : '半仓试错'
}
