/**
 * tests/war-plan.test.ts —— 「作战思路」（v1.6 作战板块重做）的离线单测。
 *
 * 为什么这个文件必须存在：这一版把作战页的产物从"用户自己点选"换成"模型给结论"，
 * 而**模型是会编的**。整个设计的立身之本就是两条可机检的纪律：
 *
 *   1. **以其他板块为基础**：素材只能来自别的页面（行情/自挖板块/选股/复盘/竞价/持仓/自选），
 *      模型说出来的票与板块名必须能在素材里查到 —— 越界的被剔除并**如实记录**
 *      （`guardWarPlan`）。编一只票、编一个板块名、编一条引文，都必须被抓住；
 *   2. **模型给默认、人可改可驳回**：三问落点/持仓动作/竞价判定按"只填空位"写进当日记录，
 *      **绝不覆盖人工答案**（`adoptWarPlan`）；驳回只清模型写的那部分（`clearAiAnswers`）。
 *
 * 另外两条成本纪律在这里钉死：同一时段已有缓存不重复生成、没有盘面素材不自动生成
 * （休市期自动跑一次只会换来"证据不足"，白花一次调用）。
 *
 * 测试只跑纯逻辑 + 一个内存版 localStorage 假体（不发网络请求、不需要真浏览器）。
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import {
  emptyWarPlanGuard,
  normalizeWarPlan,
  type WarPlan,
} from '../src/lib/ai-contract.ts'
import { guardWarPlan, materialsOf, evidenceGrounded } from '../src/lib/war-plan-guard.ts'
import {
  adoptWarPlan,
  autoGenerateDecision,
  buildWarContext,
  clearWarPlan,
  getWarPlan,
  nameIndexOf,
  planFreshness,
  planKey,
  prepareConcepts,
  saveWarPlan,
  WAR_PLAN_TTL_MS,
  type WarMaterials,
  type WarPlanRecord,
} from '../src/lib/war-plan.ts'
import { auctionTargets, screenerCandidates } from '../src/lib/war-plan-collect.ts'
import { clearAiAnswers, getDayRun, setQ1, setQ3Symbol, setVerdict } from '../src/lib/dayrun.ts'
import { saveReview } from '../src/lib/review-store.ts'
import { keyOfRecord } from '../src/lib/state-tables.ts'

// ────────────────────────────── 测试夹具 ──────────────────────────────

/** 内存版 localStorage（node 里没有 DOM）。 */
function installFakeStorage(): Map<string, string> {
  const map = new Map<string, string>()
  ;(globalThis as unknown as { localStorage: unknown }).localStorage = {
    getItem: (k: string) => (map.has(k) ? (map.get(k) as string) : null),
    setItem: (k: string, v: string) => {
      map.set(k, String(v))
    },
    removeItem: (k: string) => {
      map.delete(k)
    },
  }
  return map
}

/** 一份完整的素材（各字段都能被覆写；默认值刻意"什么都有"，便于逐项验证上限与映射）。 */
function materials(over: Partial<WarMaterials> = {}): WarMaterials {
  const base: WarMaterials = {
    day: '2026-09-12',
    stage: 'intraday',
    phase: 'trading',
    clockText: '10:12',
    windowNote: '开盘验证窗 9:30–10:00',
    breadth: {
      total: 5200,
      up: 3100,
      down: 1900,
      flat: 200,
      limitUp: 23,
      limitDown: 2,
      strongUp: 310,
      strongDown: 90,
      amountSum: 8.6e11,
      avgPct: 0.9,
    },
    regime: { temperature: 58, band: 'warm', drivers: ['涨停 23 家', '最高 5 连板'] },
    situation: 'normal',
    ladder: {
      limitUp: [
        { market: 'SZ', code: '300750', name: '宁德时代', pct: 10.01, amount: 3.2e9, streak: 2 } as never,
      ],
      limitDownCount: 2,
      boards: [
        { boardSymbol: '881001', name: '机器人概念', type: '4', limitUpCount: 5, pct: 3.2, rep: '埃斯顿', repCode: '002747' },
        { boardSymbol: '881002', name: '有色金属', type: '12', limitUpCount: 3, pct: 1.8, rep: '紫金矿业', repCode: '601899' },
      ],
      fetchedAt: 1,
    },
    events: [
      { key: 'k1', ts: 1, market: 'SZ', code: '002747', name: '埃斯顿', desc: '涨停封板', kind: 'limitUp', time: '10:03:00', value: '10.01' },
    ],
    pulses: [
      { board: '881001', name: '机器人概念', limitUp: 5, avgPct: 3.2, amountShare: 0.12, deltaLimitUp: 2, deltaAvgPct: 1.1, leader: { code: '002747', name: '埃斯顿', pct: 10.01 } },
    ],
    concepts: [
      {
        classId: 3,
        size: 12,
        intraCorr: 0.72,
        strongDensity: 0.8,
        weakChain: false,
        top: ['埃斯顿'],
        members: [
          { market: 'SZ', code: '002747', name: '埃斯顿', chgPct: 10.01, limitUp: true, corr: 0.8 },
          { market: 'SH', code: '600031', name: '三一重工', chgPct: 4.2, limitUp: false, corr: 0.7 },
        ],
        knownN: 2,
        chgMean: 7.1,
        chgMax: 10.01,
        upN: 2,
        limitUpN: 1,
        strength: 13.1,
      },
    ],
    conceptsNote: 'as_of 2026-09-12 · 可用 1 类',
    isolatedTop: [{ symbol: 'SH600519', name: '贵州茅台', chgPct: 2.1, limitUp: false }],
    screened: [
      { market: 'SH', code: '601899', name: '紫金矿业', pct: 4.5, vol_ratio: 2.4, turnover: 3.1, amount: 2.1e9 } as never,
    ],
    positions: [
      {
        symbol: 'SZ300750',
        market: 'SZ',
        code: '300750',
        name: '宁德时代',
        entryDate: '2026-09-10',
        entryPrice: 210,
        shares: 100,
        plan: { stopLoss: 198, failIf: '跌破 20 日线', note: '' },
      },
    ],
    watchlist: [{ market: 'SH', code: '600519', name: '贵州茅台' }],
    myPlan: {
      day: '2026-09-11',
      expectations: [
        {
          id: 'e1',
          symbol: 'SZ002747',
          name: '埃斯顿',
          tags: { level: 'mid', role: 'leader' },
          state: 'strong',
          scenario: '高开缩量上板',
          auctionOK: '高开 3%+',
          failIf: '低开',
          reason: '板块 5 板共振',
        },
      ],
      mainLine: ['机器人概念（埃斯顿）'],
      riskNote: '高位断板即走',
    },
    auctions: [
      { symbol: 'SZ002747', name: '埃斯顿', openPct: 4.2, climaxDir: 'buy', nearLimit: false, fakeBigThenDrop: false, expectState: 'strong', autoVerdict: 'beatExpect' },
    ],
    missing: [],
  }
  return { ...base, ...over }
}

/** 一份"全部合法"的思路（用于护栏测试的基线）。 */
function plan(over: Partial<WarPlan> = {}): WarPlan {
  const base: WarPlan = {
    insufficient: false,
    reason: '',
    summary: '机器人概念 5 板共振，权重稳住指数',
    stance: 'attack',
    sectors: [{ name: '机器人概念', source: 'board', score: 82, why: '板块 5 家涨停', members: ['SZ002747'] }],
    picks: [
      { symbol: 'SZ002747', name: '埃斯顿', role: '主攻', score: 85, reason: '板块内 2 连板且放量', trigger: '高开 3% 且量比≥2', stop: '破 5 日线' },
    ],
    q1: { value: 'strengthen', why: '涨停 23 家高于昨日 15 家' },
    q2: { value: 'normal', why: '无高低切特征' },
    actions: [{ symbol: 'SZ300750', action: 'hold', why: '未破止损 198' }],
    verdicts: [{ symbol: 'SZ002747', verdict: 'beatExpect', why: '竞价高开 4.2%' }],
    avoid: ['不追高位断板'],
    evidence: ['涨停 23 家'],
    guard: emptyWarPlanGuard(),
  }
  return { ...base, ...over }
}

/** 存量记录（用于缓存/新鲜度测试）。 */
function record(over: Partial<WarPlanRecord> = {}): WarPlanRecord {
  return {
    day: '2026-09-12',
    stage: 'intraday',
    at: Date.now(),
    plan: plan(),
    raw: '{}',
    provider: 'p',
    model: 'm',
    ms: 1200,
    ctxBytes: 4096,
    shrunk: [],
    pool: { symbols: 3, sectors: 2 },
    missing: [],
    stageLabel: '盘中',
    adopted: { written: [], kept: [] },
    ...over,
  }
}

// ─────────────────────── ① 解析层：形状与取值（模型回包不可信） ───────────────────────

test('normalizeWarPlan：素材不足的结论被原样保留（不当作解析失败）', () => {
  const p = normalizeWarPlan({ insufficient: true, reason: '行情取数失败，无法判断主线' })
  assert.equal(p?.insufficient, true)
  assert.equal(p?.reason, '行情取数失败，无法判断主线')
  assert.deepEqual(p?.sectors, [])
  assert.deepEqual(p?.picks, [])
})

test('normalizeWarPlan：非法枚举回落到安全值，分数夹取，符号归一', () => {
  const p = normalizeWarPlan({
    summary: 'x',
    stance: 'AGGRESSIVE',
    q1: { value: '增强' },
    q2: { value: 'bogus' },
    picks: [{ symbol: '002747', score: 150, role: '主攻' }, { symbol: 'nope' }],
    sectors: [{ name: '机器人概念', source: '瞎写', members: ['002747', 'bogus'] }],
    actions: [{ symbol: '300750', action: '加仓' }],
    verdicts: [{ symbol: '002747', verdict: '乱写' }],
  })
  assert.equal(p?.stance, 'wait', '非法 stance 落到最保守的 wait')
  assert.equal(p?.q1?.value, 'flat', '中文取值不认 → flat')
  assert.equal(p?.q2?.value, 'normal')
  assert.equal(p?.picks.length, 1, '无符号的候选被丢掉')
  assert.equal(p?.picks[0]?.symbol, 'SZ002747', '6 位代码按代码段补市场前缀')
  assert.equal(p?.picks[0]?.score, 100, '分数夹取到 100')
  assert.equal(p?.sectors[0]?.source, 'concept', '非法来源回落')
  assert.deepEqual(p?.sectors[0]?.members, ['SZ002747'], '成员里的垃圾符号被剔除')
  assert.equal(p?.actions[0]?.action, 'hold', '非法动作回落')
  assert.equal(p?.verdicts[0]?.verdict, 'confirm', '非法判定回落')
})

test('normalizeWarPlan：数量上限（方向 ≤3 / 候选 ≤5 且按分排序）', () => {
  const p = normalizeWarPlan({
    summary: 'x',
    sectors: [1, 2, 3, 4].map((i) => ({ name: `板块${i}` })),
    picks: [1, 2, 3, 4, 5, 6].map((i) => ({ symbol: `SH60000${i}`, score: i * 10 })),
  })
  assert.equal(p?.sectors.length, 3)
  assert.equal(p?.picks.length, 5)
  assert.deepEqual(
    p?.picks.map((x) => x.score),
    [50, 40, 30, 20, 10],
    '候选按把握分降序（模型给的顺序不可信）',
  )
})

test('normalizeWarPlan：什么都没有 = 解析失败（null），而不是假装成功', () => {
  assert.equal(normalizeWarPlan({}), null)
  assert.equal(normalizeWarPlan({ summary: '' }), null)
  assert.equal(normalizeWarPlan('不是对象'), null)
})

test('normalizeWarPlan：avoid/evidence 写成裸字符串也认（模型的常见写法）', () => {
  const p = normalizeWarPlan({ summary: 'x', avoid: '不追高', evidence: '涨停 23 家' })
  assert.deepEqual(p?.avoid, ['不追高'])
  assert.deepEqual(p?.evidence, ['涨停 23 家'])
})

// ─────────────── ② 护栏层：只能素材里有的东西（"不是空穴来风"） ───────────────

test('guardWarPlan：素材外的票被剔除并记录，素材内的保留', () => {
  const ctx = buildWarContext(materials())
  const p = guardWarPlan(
    plan({
      picks: [
        { symbol: 'SZ002747', name: '埃斯顿', role: '主攻', score: 85, reason: 'r', trigger: 't', stop: 's' },
        { symbol: 'SH601398', name: '工商银行', role: '编的', score: 90, reason: 'r', trigger: 't', stop: 's' },
      ],
      actions: [{ symbol: 'SH601398', action: 'clear', why: '编的' }],
      verdicts: [{ symbol: 'SH601398', verdict: 'trap', why: '编的' }],
      sectors: [{ name: '机器人概念', source: 'board', score: 80, why: 'w', members: ['SZ002747', 'SH601398'] }],
    }),
    ctx,
  )
  assert.deepEqual(p.picks.map((x) => x.symbol), ['SZ002747'], '素材外的候选不进最终结论')
  assert.deepEqual(p.actions, [], '素材外的持仓动作被剔除')
  assert.deepEqual(p.verdicts, [])
  assert.deepEqual(p.sectors[0]?.members, ['SZ002747'], '方向成员同样过白名单')
  assert.equal(p.guard.droppedSymbols.length, 4, '4 处越界点名全部留痕（候选/动作/判定/成员）')
  assert.ok(p.guard.droppedSymbols.every((s) => s.includes('SH601398')))
  assert.ok(p.guard.symbolPool >= 4, '白名单规模回传（界面要显示"模型能点名几只"）')
})

test('guardWarPlan：自造的板块名被剔除（方向名必须逐字取自素材）', () => {
  const ctx = buildWarContext(materials())
  const p = guardWarPlan(
    plan({
      sectors: [
        { name: '机器人概念', source: 'board', score: 80, why: 'w', members: [] },
        { name: '人形机器人核心零部件', source: 'concept', score: 90, why: '听起来很专业', members: [] },
      ],
    }),
    ctx,
  )
  assert.deepEqual(p.sectors.map((s) => s.name), ['机器人概念'])
  assert.equal(p.guard.droppedSectors.length, 1)
  assert.ok(p.guard.droppedSectors[0]?.includes('人形机器人核心零部件'))
  assert.equal(p.guard.sectorPool, 2, '方向名池 = 板块榜名（2 个）')
})

test('guardWarPlan：素材里一个板块名都没有时，方向一律剔除（宁可不说）', () => {
  const ctx = buildWarContext(materials({ ladder: { limitUp: [], limitDownCount: 0, boards: [], fetchedAt: 1 } }))
  const p = guardWarPlan(plan({ sectors: [{ name: '机器人概念', source: 'board', score: 80, why: 'w', members: [] }] }), ctx)
  assert.deepEqual(p.sectors, [])
  assert.equal(p.guard.sectorPool, 0)
  assert.equal(p.guard.droppedSectors.length, 1)
})

test('guardWarPlan：引文反查（数字/名字逐字命中才算落地）', () => {
  const ctx = buildWarContext(materials())
  const p = guardWarPlan(
    plan({ evidence: ['涨停 23 家', '机器人概念 5 家涨停', '主力资金净流入 88.88 亿', '某个不存在的题材'] }),
    ctx,
  )
  assert.equal(p.guard.grounded, 2, '「23」与板块名可反查')
  assert.equal(p.guard.ungrounded.length, 2)
  assert.ok(p.guard.ungrounded.some((e) => e.includes('88.88')))
  assert.equal(p.evidence.length, 4, '未落地的引文保留原文并标注（记录而不丢弃）')
})

test('evidenceGrounded：单独验证反查口径的边界', () => {
  const m = materialsOf({ a: 23, b: '机器人概念' })
  assert.equal(evidenceGrounded('涨停 23 家', m), true, '数字命中')
  assert.equal(evidenceGrounded('机器人概念共振', m), true, '名字命中')
  assert.equal(evidenceGrounded('涨停 9 家', m), false, '数字不命中（不是"含数字就算"）')
  assert.equal(evidenceGrounded('', m), false)
})

test('guardWarPlan：素材不足的回答不做剔除，只回填白名单规模', () => {
  const ctx = buildWarContext(materials())
  const insufficient = normalizeWarPlan({ insufficient: true, reason: '休市无数' })
  assert.ok(insufficient !== null)
  const p = guardWarPlan(insufficient, ctx)
  assert.equal(p.insufficient, true)
  assert.equal(p.guard.droppedSymbols.length, 0)
  assert.equal(p.guard.sectorPool, 2)
})

// ─────────────────────── ③ 组装层：素材来自哪些板块 ───────────────────────

test('buildWarContext：方向名池 = 行情页板块榜名；票一律标准符号', () => {
  const ctx = buildWarContext(materials()) as Record<string, unknown>
  assert.deepEqual(ctx.sectorUniverse, ['机器人概念', '有色金属'])
  assert.equal((ctx.watchlist as Array<{ symbol: string }>)[0]?.symbol, 'SH600519', '自选是 market+code，要转标准符号')
  assert.equal((ctx.ladder as Array<{ symbol: string }>)[0]?.symbol, 'SZ300750')
  assert.equal((ctx.concepts as Array<{ members: Array<{ symbol: string }> }>)[0]?.members[1]?.symbol, 'SH600031')
  assert.equal((ctx.positions as Array<{ symbol: string }>)[0]?.symbol, 'SZ300750')
  assert.equal((ctx.screened as Array<{ symbol: string }>)[0]?.symbol, 'SH601899', '选股候选也进素材')
})

test('buildWarContext：素材缺口原样进上下文（模型要知道自己少看了什么）', () => {
  const ctx = buildWarContext(materials({ missing: ['自挖板块：引擎不可用'] })) as Record<string, unknown>
  assert.deepEqual(ctx.missing, ['自挖板块：引擎不可用'])
  assert.equal((ctx.market as { breadth: { amountYi: number } }).breadth.amountYi, 8600, '成交额转亿且保留两位')
})

test('nameIndexOf：名称一律回查素材（模型不给名字，也就编不出名字）', () => {
  const map = nameIndexOf(materials())
  assert.equal(map.get('SZ300750'), '宁德时代')
  assert.equal(map.get('SH600519'), '贵州茅台')
  assert.equal(map.get('SZ002747'), '埃斯顿')
  assert.equal(map.get('SH601899'), '紫金矿业')
  assert.equal(map.get('SH601398'), undefined, '素材里没有的票查不到名字')
})

test('prepareConcepts：弱链伪类不进素材，按强度排序，并说明排除了几个', () => {
  const rows = [
    { classId: 1, size: 10, intraCorr: 0.7, strongDensity: 0.8, weakChain: false, strength: 5, members: [], top: [], knownN: 0, chgMean: 0, chgMax: 0, upN: 0, limitUpN: 0 },
    { classId: 2, size: 40, intraCorr: 0.2, strongDensity: 0.1, weakChain: true, strength: 99, members: [], top: [], knownN: 0, chgMean: 0, chgMax: 0, upN: 0, limitUpN: 0 },
    { classId: 3, size: 8, intraCorr: 0.66, strongDensity: 0.7, weakChain: false, strength: 20, members: [], top: [], knownN: 0, chgMean: 0, chgMax: 0, upN: 0, limitUpN: 0 },
  ] as unknown as Parameters<typeof prepareConcepts>[0] extends null ? never : NonNullable<Parameters<typeof prepareConcepts>[0]>['classes']
  const out = prepareConcepts({ ok: true, asOf: '2026-09-12', classes: rows, notes: [], params: { minCorr: 0.6 } })
  assert.deepEqual(out.rows.map((r) => r.classId), [3, 1], '强度高的在前，弱链类被排除')
  assert.match(out.note, /排除 1 个/)
})

test('prepareConcepts：引擎不可用 = 明确说明（不是空数组了事）', () => {
  const out = prepareConcepts({ ok: false, asOf: '', classes: [], notes: ['引擎超时'] })
  assert.deepEqual(out.rows, [])
  assert.match(out.note, /引擎超时/)
  assert.match(prepareConcepts(null).note, /未取数/)
})

test('screenerCandidates：在既有全 A 快照上跑预设（零额外请求）', () => {
  const rows = [
    { market: 'SH', code: '601899', name: '紫金矿业', pct: 4.5, vol_ratio: 2.4, turnover: 5.6, amount: 2.1e9, total_market_cap_ab: 5e11 },
    { market: 'SZ', code: '000001', name: '平安银行', pct: 0.2, vol_ratio: 1.0, turnover: 0.5, amount: 1e9, total_market_cap_ab: 2e11 },
  ] as unknown as Parameters<typeof screenerCandidates>[0]
  const out = screenerCandidates(rows as never)
  assert.deepEqual(out.map((r) => r.code), ['601899'], '只有"放量上攻"命中')
  assert.deepEqual(screenerCandidates(null), [], '快照缺失时给空，不抛')
})

test('auctionTargets：预期清单优先、自选补位、去重且限量', () => {
  const targets = auctionTargets(
    materials().myPlan?.expectations ?? [],
    [{ market: 'SH', code: '600519', name: '贵州茅台' }, { market: 'SZ', code: '002747', name: '埃斯顿' }],
  )
  assert.deepEqual(targets.map((t) => t.symbol), ['SZ002747', 'SH600519'], '自选里的重复项被去掉')
  assert.equal(targets[0]?.expectState, 'strong', '带昨日预期状态（系统初判要用）')
})

// ─────────────────────── ④ 成本纪律：什么时候该跑模型 ───────────────────────

test('autoGenerateDecision：同时段已有新鲜思路 → 不跑（省一次模型调用）', () => {
  const now = Date.now()
  const d = autoGenerateDecision({ hasMaterials: true, existing: record({ at: now - 60_000 }), now })
  assert.equal(d.run, false)
  assert.match(d.why, /已有时段内的思路/)
})

test('autoGenerateDecision：没有盘面素材（休市/取数失败）→ 不跑', () => {
  const d = autoGenerateDecision({ hasMaterials: false, existing: null, now: Date.now() })
  assert.equal(d.run, false)
  assert.match(d.why, /不自动生成/)
})

test('autoGenerateDecision：素材在手且本时段还没算过 → 跑一次', () => {
  assert.equal(autoGenerateDecision({ hasMaterials: true, existing: null, now: Date.now() }).run, true)
})

test('autoGenerateDecision：过期（stale）→ 可以重算（不自动反复跑由调用方闸门保证）', () => {
  const now = Date.now()
  const stale = record({ at: now - WAR_PLAN_TTL_MS - 1000 })
  assert.equal(planFreshness(stale, now), 'stale')
  assert.equal(autoGenerateDecision({ hasMaterials: true, existing: stale, now }).run, true)
})

// ─────────────────────── ⑤ 存档：按时段缓存 + 与 host 表对齐 ───────────────────────

test('存档：写读清 + 记录键与 host 表口径一致', () => {
  const store = installFakeStorage()
  saveWarPlan(record())
  assert.ok(getWarPlan('2026-09-12', 'intraday') !== null, '按时段取回')
  assert.equal(getWarPlan('2026-09-12', 'tail'), null, '别的时段互不影响（竞价/盘中/尾盘各一份）')
  assert.ok(store.has('dsh-stock-panel:war-plan:v1'), '落 localStorage（host 域同步的镜像）')
  // hydrate/sync 的无损契约：state-tables 的记录键必须就是本模块的 planKey
  assert.equal(keyOfRecord('war_plans', { day: '2026-09-12', stage: 'intraday' }), planKey('2026-09-12', 'intraday'))
  clearWarPlan('2026-09-12', 'intraday')
  assert.equal(getWarPlan('2026-09-12', 'intraday'), null)
})

test('guardWarPlan：白名单规模回传（界面要显示"模型能点名几只票/几个方向"）', () => {
  const p = guardWarPlan(plan(), buildWarContext(materials()))
  assert.equal(p.guard.sectorPool, 2)
  assert.ok(p.guard.symbolPool >= 5, `符号白名单应覆盖素材里所有票，实际 ${p.guard.symbolPool}`)
})

// ─────────────── ⑥ 采纳：模型给默认、人可改、可驳回（绝不复写人工答案） ───────────────

test('adoptWarPlan：空位按模型结论填，全部标 from=ai', () => {
  installFakeStorage()
  const day = '2026-03-02'
  const ad = adoptWarPlan(day, plan(), materials().positions)
  assert.ok(ad.written.some((w) => w.startsWith('Q1')))
  assert.ok(ad.written.some((w) => w.startsWith('Q2')))
  assert.ok(ad.written.some((w) => w.includes('SZ300750')))
  const run = getDayRun(day)
  assert.equal(run?.q1?.value, 'strengthen')
  assert.equal(run?.q1?.from, 'ai', '来源必须标出来（复盘时要能分辨"这句是模型说的"）')
  assert.equal(run?.q2?.from, 'ai')
  assert.equal(run?.q3?.bySymbol.SZ300750?.from, 'ai')
})

test('adoptWarPlan：人工答案一律不覆盖（第二次采纳 = 全部保留）', () => {
  installFakeStorage()
  const day = '2026-03-03'
  adoptWarPlan(day, plan(), materials().positions)
  const second = adoptWarPlan(day, plan(), materials().positions)
  assert.deepEqual(second.written, [], '第二次没有任何可写项')
  assert.ok(second.kept.length >= 3, '已答的 Q1/Q2/Q3 都在"保留"里')
})

test('adoptWarPlan：人自己改了之后，重新生成的思路不会把它改回去', () => {
  installFakeStorage()
  const day = '2026-03-04'
  setQ1(day, 'weaken') // 人工判断：衰减
  const ad = adoptWarPlan(day, plan(), materials().positions)
  assert.equal(getDayRun(day)?.q1?.value, 'weaken', '人工答案保住')
  assert.equal(getDayRun(day)?.q1?.from, 'manual', '来源仍是人工')
  assert.ok(ad.kept.some((k) => k.startsWith('Q1')))
})

test('adoptWarPlan：已不在持仓台账的动作不写（思路可能基于几轮前的素材）', () => {
  installFakeStorage()
  const day = '2026-03-05'
  const ad = adoptWarPlan(day, plan(), [])
  assert.equal(getDayRun(day)?.q3?.bySymbol.SZ300750, undefined)
  assert.ok(ad.kept.some((k) => k.includes('不在持仓台账')))
  // 空仓且模型没给持仓动作 → 自动打"空仓观望"钩
  const ad2 = adoptWarPlan(day, plan({ actions: [] }), [])
  assert.equal(getDayRun(day)?.q3?.idle, true)
  assert.ok(ad2.written.some((w) => w.includes('空仓观望')))
})

test('adoptWarPlan：竞价判定只对预期清单里的票生效', () => {
  installFakeStorage()
  const day = '2026-03-06'
  saveReview({
    day,
    savedAt: Date.now(),
    breadth: { up: 1, down: 1, limitUp: 1, limitDown: 0, amountYi: 1 },
    regime: null,
    mainLine: [],
    expectations: [
      {
        id: 'e1',
        symbol: 'SZ002747',
        name: '埃斯顿',
        tags: { level: 'mid', role: 'leader' },
        state: 'strong',
        scenario: '',
        auctionOK: '',
        failIf: '',
        reason: '',
      },
    ],
    notable: [],
  })
  const ad = adoptWarPlan(
    day,
    plan({
      verdicts: [
        { symbol: 'SZ002747', verdict: 'beatExpect', why: '竞价强' },
        { symbol: 'SZ300750', verdict: 'trap', why: '清单外' },
      ],
    }),
    materials().positions,
  )
  assert.equal(getDayRun(day)?.verdicts.SZ002747?.verdict, 'beatExpect')
  assert.equal(getDayRun(day)?.verdicts.SZ002747?.from, 'ai')
  assert.equal(getDayRun(day)?.verdicts.SZ300750, undefined, '清单外的票没有对照基准，不写判定')
  assert.ok(ad.kept.some((k) => k.includes('不在预期清单')))
})

test('adoptWarPlan：素材不足的思路不写任何东西', () => {
  installFakeStorage()
  const day = '2026-03-07'
  const ad = adoptWarPlan(day, plan({ insufficient: true, reason: '休市无数', sectors: [], picks: [], q1: null, q2: null, actions: [], verdicts: [] }), [])
  assert.deepEqual(ad.written, [])
  assert.deepEqual(ad.kept, [])
})

test('clearAiAnswers：驳回只清模型写的，人工点的一律不动', () => {
  installFakeStorage()
  const day = '2026-03-08'
  adoptWarPlan(day, plan(), materials().positions)
  setQ1(day, 'weaken') // 人工改 Q1
  setQ3Symbol(day, 'SZ300750', 'reduce') // 人工改 Q3
  setVerdict(day, 'SZ002747', 'falsify') // 人工改判定
  clearAiAnswers(day)
  const run = getDayRun(day)
  assert.equal(run?.q1?.value, 'weaken', '人工的 Q1 留下')
  assert.equal(run?.q2, undefined, '模型写的 Q2 被清掉')
  assert.equal(run?.q3?.bySymbol.SZ300750?.action, 'reduce')
  assert.equal(run?.verdicts.SZ002747?.verdict, 'falsify')
})
